// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  results: dynamic(() => import("./Results")),
  steps: dynamic(() => import("./Steps")),
};
